#!/usr/bin/env bash

###########################################\
##/       Herbstluftwm Config File       \##\
##\__Config File Created by Ocillacubes__/##/
###########################################/


hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn ${TERMINAL:-xterm} # use your $TERMINAL with xterm as fallback
hc keybind $Mod-w spawn bmks
hc keybind $Mod-Shift-w spawn ${BROWSER:-firefox}
hc keybind $Mod-d spawn ~/.config/rofi/bin/launcher_ribbon
hc keybind $Mod-Shift-d spawn ${LAUNCHER:-dmenu_run}
hc keybind $Mod-p spawn ${PASS_MGR:-keepassxc}
hc keybind $Mod-r spawn ${FILE_MGR:-pcmanfm}
hc keybind $Mod-v spawn ${VNC_CLIENT:-remmina}
hc keybind $Mod-Shift-v spawn ${VM_CLIENT:-virt-manager}
hc keybind $Mod-n spawn ${NEWS_CLIENT:-liferea}
hc keybind $Mod-Shift-m spawn ${EMAIL_CLIENT:-claws-mail}
hc keybind $Mod-m spawn ${MUSIC_CLIENT:-quodlibet}

hc keybind $Mod-e spawn emacsclient -c
hc keybind $Mod-b spawn hydrus-client
hc keybind $Mod-g spawn gimp
hc keybind $Mod-Shift-g spawn jellyfinmediaplayer

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-Shift-o split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
# hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tag_names=( "1" "2" "3" "4" "5" "6" "7" "8" "9" "0" )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-Shift-q remove
hc keybind $Mod-Shift-f floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1
# Media Controls
hc keybind XF86AudioRaiseVolume spawn vol pulse up #Increase Volume
hc keybind XF86AudioLowerVolume spawn vol pulse down #Decrease volume
hc keybind XF86AudioMute spawn vol pulse mute #Mute audio
hc keybind $Mod-XF86AudioRaiseVolume spawn vol pulsemic up #Increase mic volume
hc keybind $Mod-XF86AudioLowerVolume spawn vol pulsemic down #Decrease mic volume
hc keybind $Mod-XF86AudioMute spawn vol pulsemic mute #mute mic
hc keybind XF86AudioPrev spawn playerctl previous #Previous track
hc keybind XF86AudioNext spawn playerctl next #Next track
hc keybind XF86AudioPlay spawn playerctl play-pause #Toggle play/pause
hc keybind XF86AudioStop spawn playerctl stop #Stop track

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
# hc keybind $Mod-BackSpace   cycle_monitor
# hc keybind $Mod-Tab         cycle_all +1
# hc keybind $Mod-Shift-Tab   cycle_all -1
# hc keybind $Mod-Tab cycle
# hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule class=HydrusClient floating=on floatplacement=center focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc set focus_follows_mouse 1

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 2560x1440+0+0 2560x1405+2560+35 1920x1080+5120+0
# or simply:
bash ~/.local/scripts/wal
hc detect_monitors
